### ISSUE TITLE
apply mypy on test suite

### ISSUE THREAD

**Issue by jugmac00** [jugmac00/flask-reuploaded#90]

**Comment by Alig1493** [comment]
you want `mypy` working for just the test suite or the entire project? I mean the package itself is just a static type checker.

**Comment by jugmac00** [comment]
`mypy` is already applied on the app, see https://github.com/jugmac00/flask-reuploaded/blob/ecaceffebf247dea40040246c319aa6a0f0e0ff8/tox.ini#L33 but not yet on the test suite

**Comment by jugmac00** [comment]
Down to a couple of errors, which are currently type ignored

**Comment by jugmac00** [comment]
(Mostly) fixed by #117
